config/routes.rb
Rails.application.routes.draw do
  resources :comisiones
  resources :topes
  get 'home/index'
  get 'home/estado_cuenta', as: :estado_cuenta

  resources :gastos
  resources :socios
  resources :proveedores
  resources :depositos
  resources :apartados, only: [:show]
  resources :previsiones
  resources :rubros
  resource :prevision_activa, only: [:show, :update]
  devise_for :usuarios, skip: [:registrations]

  root 'home#index'

end

app/models/apartado.rb
class Apartado < ActiveRecord::Base
  # == Associations ==
  belongs_to :rubro
  belongs_to :prevision
  has_many :gastos
  has_many :socios, -> { distinct }, through: :gastos

  # == Validations ==
  validates :rubro, :prevision, :monto_maximo, presence: true
  validates :monto_maximo, numericality: { greater_than: 0 }
  validate :monto_no_rebasa_monto_de_prevision

  # == Scopes ==
  scope :de_prevision,              -> prevision { where(prevision: prevision) }
  scope :de_prevision_activa,       -> { de_prevision(Prevision.default) }
  scope :para_seleccionar_en_gasto, -> { includes(:prevision, :rubro).de_prevision_activa }

  # == Methods ==

  delegate :monto, to: :prevision, prefix: true, allow_nil: true

  def fecha_inicial
    prevision.fecha_inicial
  end

  def fecha_final
    prevision.fecha_final
  end

  def to_s
    "#{ rubro } - #{ prevision.fecha_inicial.year }"
  end

  def monto_gastado
    gastos.sum(:monto)
  end

  def suma_monto_gastado
    gastos.to_a.sum(&:monto)
  end

  def monto_gastado_por_socio(socio)
    gastos.de_socio(socio).sum(:monto)
  end

private

  def monto_no_rebasa_monto_de_prevision
    errors.add :monto_maximo, :exceeds_monto_prevision if prevision_monto.to_f < monto_maximo.to_f
  end
end

# == Schema Information
#
# Table name: apartados
#
#  id           :integer          not null, primary key
#  monto_maximo :decimal(, )
#  rubro_id     :integer
#  prevision_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_apartados_on_prevision_id  (prevision_id)
#  index_apartados_on_rubro_id      (rubro_id)
#
# Foreign Keys
#
#  fk_rails_a7b482130a  (rubro_id => rubros.id)
#  fk_rails_b96ecf8df7  (prevision_id => previsiones.id)
#

app/controllers/apartados_controller.rb
class ApartadosController < ApplicationController
  before_action :set_apartado, only: [:show, :edit, :update, :destroy]

  # GET /apartados
  # GET /apartados.json
  def index
    @apartados = Apartado.all
  end

  # GET /apartados/1
  # GET /apartados/1.json
  def show
  end

  # GET /apartados/new
  def new
    @apartado = Apartado.new
  end

  # GET /apartados/1/edit
  def edit
  end

  # POST /apartados
  # POST /apartados.json
  def create
    @apartado = Apartado.new(apartado_params)

    respond_to do |format|
      if @apartado.save
        format.html { redirect_to @apartado, notice: 'Apartado guardado correctamente.' }
        format.json { render :show, status: :created, location: @apartado }
      else
        format.html { render :new }
        format.json { render json: @apartado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartados/1
  # PATCH/PUT /apartados/1.json
  def update
    respond_to do |format|
      if @apartado.update(apartado_params)
        format.html { redirect_to @apartado, notice: 'Apartado actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @apartado }
      else
        format.html { render :edit }
        format.json { render json: @apartado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartados/1
  # DELETE /apartados/1.json
  def destroy
    @apartado.destroy
    respond_to do |format|
      format.html { redirect_to apartados_url, notice: 'Apartado eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartado
      @apartado = Apartado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartado_params
      params.require(:apartado).permit(:monto_maximo, :rubro_id, :prevision_id)
    end
end

app/helpers/apartados_helper.rb
module ApartadosHelper
end

app/views/apartados/_form.html.haml
= simple_form_for(@apartado) do |f|
  = f.error_notification

  .form-inputs
    = f.input :monto_maximo
    = f.association :rubro
    = f.association :prevision

  .form-actions
    = f.button :submit
    = link_to 'Cancelar', apartados_path, class: 'btn btn-danger'

app/views/apartados/edit.html.haml
%h2
  %i.fa
  &nbsp;
  Editar Apartado

%hr

= render 'form'

app/views/apartados/index.html.haml
.pull-right
  = link_to new_apartado_path, class: 'btn btn-lg btn-primary' do
    %i.fa.fa-plus
    Nuevo Apartado

%h1
  %i.fa
  &nbsp;
  Apartados

%hr

%table.table
  %thead
    %tr
      %th Monto maximo
      %th Rubro
      %th Prevision
      %th Acciones
      
  %tbody
    - @apartados.each do |apartado|
      %tr
        %td= apartado.monto_maximo
        %td= apartado.rubro
        %td= apartado.prevision
        %td
          .btn-group
            = link_to apartado, class: 'btn btn-sm btn-secondary', title: 'Detalles' do
              %i.fa.fa-search-plus
            = link_to edit_apartado_path(apartado), class: 'btn btn-sm btn-secondary', title: 'Modificar' do
              %i.fa.fa-edit
            = link_to apartado, method: :delete, data: { confirm: '¿Estás seguro de borrarlo?'}, class: 'btn btn-sm btn-danger', title: 'Eliminar' do
              %i.fa.fa-trash

app/views/apartados/new.html.haml
%h2
  %i.fa
  &nbsp;
  Nuevo Apartado

%hr

= render 'form'

app/views/apartados/show.html.haml
%h2
  %i.fa.fa-bicycle
  &nbsp;
  Detalles de Apartado

%hr

.form-horizontal
  .form-group
    %label.col-sm-3.control-label
      Rubro:
    .col-sm-9
      %p.form-control-static
        = @apartado.rubro
  .form-group
    %label.col-sm-3.control-label
      Prevision:
    .col-sm-9
      %p.form-control-static
        = @apartado.prevision
  .form-group
    %label.col-sm-3.control-label
      Monto máximo por socio:
    .col-sm-9
      %p.form-control-static
        = number_to_currency @apartado.monto_maximo
  .form-group
    - @apartado.socios.each do |socio|
      .form-group
        %label.col-sm-3.control-label
          = socio
        .col-sm-9
          %p.form-control-static
            = mostrar_montos(monto: socio.monto_gastado(@apartado), monto_limite: @apartado.monto_maximo, ocultar_limite: true)

.pull-right
  = link_to root_path, class: 'btn btn-default' do
    %i.fa.fa-arrow-left
    Regresar