config/routes.rb
Rails.application.routes.draw do
  resources :comisiones
  resources :topes
  get 'home/index'
  get 'home/estado_cuenta', as: :estado_cuenta

  resources :gastos
  resources :socios
  resources :proveedores
  resources :depositos
  resources :apartados, only: [:show]
  resources :previsiones
  resources :rubros
  resource :prevision_activa, only: [:show, :update]
  devise_for :usuarios, skip: [:registrations]

  root 'home#index'

end

app/controllers/previsiones_controller.rb
class PrevisionesController < ApplicationController
  before_action :set_prevision, only: [:show, :edit, :update, :destroy]

  # GET /previsiones
  # GET /previsiones.json
  def index
    @previsiones = Prevision.para_listar
  end

  # GET /previsiones/1
  # GET /previsiones/1.json
  def show
    @prevision = Prevision.includes(topes: :socio, apartados: :rubro).find(params[:id])
  end

  # GET /previsiones/new
  def new
    @prevision = Prevision.new
    @prevision.topes.build
    @prevision.apartados.build
  end

  # GET /previsiones/1/edit
  def edit
  end

  # POST /previsiones
  # POST /previsiones.json
  def create
    @prevision = Prevision.new(prevision_params)

    respond_to do |format|
      if @prevision.save
        format.html { redirect_to @prevision, notice: 'Previsión guardada correctamente.' }
        format.json { render :show, status: :created, location: @prevision }
      else
        format.html { render :new }
        format.json { render json: @prevision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /previsiones/1
  # PATCH/PUT /previsiones/1.json
  def update
    respond_to do |format|
      if @prevision.update(prevision_params)
        format.html { redirect_to @prevision, notice: 'Previsión actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @prevision }
      else
        format.html { render :edit }
        format.json { render json: @prevision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /previsiones/1
  # DELETE /previsiones/1.json
  def destroy
    @prevision.destroy
    respond_to do |format|
      format.html { redirect_to previsiones_url, notice: 'Previsión eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prevision
      @prevision = Prevision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prevision_params
      params.require(:prevision).permit(
        :periodo,
        :monto_remanente,
        :monto_presupuestado,
        apartados_attributes: [:id, :rubro_id, :monto_maximo, :_destroy],
        topes_attributes: [:id, :socio_id, :monto, :monto_reservado, :_destroy]
      )
    end
end

app/helpers/previsiones_helper.rb
module PrevisionesHelper
end

app/views/previsiones/_apartados.html.haml
.panel.panel-default
  .panel-heading
    Rubros
    .pull-right
      = f.link_to_add :apartados, class: 'btn btn-xs btn-success', data: { target: '#apartados-prevision' } do
        %i.fa.fa-archive
        Agregar apartado
  %table.table
    %thead
      %tr
        %th Nombre
        %th Monto
        %th
    %tbody#apartados-prevision
      = f.simple_fields_for :apartados, wrapper: false, defaults: { label: false, input_html: { class: 'form-control' } } do |fs|
        %tr.fields
          %td= fs.association :rubro
          %td= fs.input :monto_maximo
          %td
            = fs.link_to_remove class: 'btn btn-sm btn-danger' do
              %i.fa.fa-times

app/views/previsiones/_form.html.haml
= simple_nested_form_for(@prevision) do |f|
  = f.error_notification

  .row.form-inputs
    .col-md-4
      = f.input :periodo
    .col-md-4
      = f.input :monto_remanente
    .col-md-4
      = f.input :monto_presupuestado

  %hr

  .row
    .col-md-6
      = render 'topes', f: f

    .col-md-6
      = render 'apartados', f: f

  .form-actions.pull-right
    = f.button :submit
    = link_to 'Cancelar', previsiones_path, class: 'btn btn-danger'

app/views/previsiones/_topes.html.haml
.panel.panel-default
  .panel-heading
    Socios
    .pull-right
      = f.link_to_add :topes, class: 'btn btn-xs btn-success', data: { target: '#socios-prevision' } do
        %i.fa.fa-user-plus
        Agregar socio
  %table.table
    %thead
      %tr
        %th Nombre
        %th Tope
        %th Reservado
        %th
    %tbody#socios-prevision
      = f.simple_fields_for :topes, wrapper: false, defaults: { label: false, input_html: { class: 'form-control' } } do |fs|
        %tr.fields
          %td= fs.association :socio
          %td= fs.input :monto
          %td= fs.input :monto_reservado
          %td
            = fs.link_to_remove class: 'btn btn-sm btn-danger' do
              %i.fa.fa-times

app/views/previsiones/edit.html.haml
%h2
  %i.fa
  &nbsp;
  Editar Previsión

%hr

= render 'form'

app/views/previsiones/index.html.haml
.pull-right
  = link_to new_prevision_path, class: 'btn btn-lg btn-primary' do
    %i.fa.fa-plus
    Nueva Previsión

%h1
  %i.fa.fa-bank
  &nbsp;
  Previsiones

%hr

%table.table
  %thead
    %tr
      %th Fecha inicial
      %th Fecha final
      %th Remanente
      %th Presupuestado
      %th Monto total
      %th Acciones
      
  %tbody
    - @previsiones.each do |prevision|
      %tr
        %td= l prevision.fecha_inicial, format: :long
        %td= l prevision.fecha_final, format: :long
        %td= number_to_currency prevision.monto_remanente
        %td= number_to_currency prevision.monto_presupuestado
        %td= number_to_currency prevision.monto
        %td
          .btn-group
            = link_to prevision, class: 'btn btn-sm btn-secondary', title: 'Detalles' do
              %i.fa.fa-search-plus
            = link_to edit_prevision_path(prevision), class: 'btn btn-sm btn-secondary', title: 'Modificar' do
              %i.fa.fa-edit
            = link_to prevision, method: :delete, data: { confirm: '¿Estás seguro de borrarlo?'}, class: 'btn btn-sm btn-danger', title: 'Eliminar' do
              %i.fa.fa-trash

app/views/previsiones/new.html.haml
%h2
  %i.fa.fa-bank
  &nbsp;
  Nueva Previsión

%hr

= render 'form'

app/views/previsiones/show.html.haml
%h2
  %i.fa.fa-bank
  &nbsp;
  Detalles de Previsión

%hr

.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        Información general
      .panel-body.form-horizontal
        .form-group
          %label.col-sm-3.control-label
            Fecha inicial:
          .col-sm-9
            %p.form-control-static
              = l @prevision.fecha_inicial, format: :long
        .form-group
          %label.col-sm-3.control-label
            Fecha final:
          .col-sm-9
            %p.form-control-static
              = l @prevision.fecha_final, format: :long
        .form-group
          %label.col-sm-3.control-label
            Monto remanente:
          .col-sm-9
            %p.form-control-static
              = number_to_currency @prevision.monto_remanente
        .form-group
          %label.col-sm-3.control-label
            Monto presupuestado:
          .col-sm-9
            %p.form-control-static
              = number_to_currency @prevision.monto_presupuestado
        .form-group
          %label.col-sm-3.control-label
            Monto total:
          .col-sm-9
            %p.form-control-static
              = number_to_currency @prevision.monto


  .col-md-6
    .panel.panel-default
      .panel-heading
        %i.fa.fa-line-chart
        &nbsp;
        Estado de previsión
      .panel-body.form-horizontal
        .form-group
          %label.col-sm-6.control-label
            Monto depositado:
          .col-sm-6
            %p.form-control-static
              = number_to_currency @prevision.monto_depositado
        .form-group
          %label.col-sm-6.control-label
            Monto gastado:
          .col-sm-6
            %p.form-control-static
              = number_to_currency @prevision.monto_gastado
        .form-group
          %label.col-sm-6.control-label
            Monto disponible:
          .col-sm-6
            %p.form-control-static
              = number_to_currency @prevision.monto - @prevision.monto_gastado_o_reservado
        .form-group
          %label.col-sm-6.control-label
            Monto reservado:
          .col-sm-6
            %p.form-control-static
              = number_to_currency @prevision.monto_reservado
        .form-group
          %label.col-sm-6.control-label
            Saldo en bancos:
          .col-sm-6
            %p.form-control-static
              = number_to_currency @prevision.monto_depositado - @prevision.monto_gastado
        .form-group
          %label.col-sm-6.control-label
            Monto por depositar:
          .col-sm-6
            %p.form-control-static
              = number_to_currency @prevision.monto - @prevision.monto_depositado
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        %i.fa.fa-dollar
        &nbsp;
        Topes
      %table.table
        %thead
          %tr
            %th Socio
            %th Tope
            %th Reservado
            %th
        %tbody
          - @prevision.topes.each do |tope|
            %tr
              %td= tope.socio
              %td= number_to_currency tope.monto
              %td= number_to_currency tope.monto_reservado
              %td
  .col-md-6
    .panel.panel-default
      .panel-heading
        %i.fa.fa-archive
        &nbsp;
        Apartados
      %table.table
        %thead
          %tr
            %th Rubro
            %th Monto
            - if @prevision == prevision_activa
              %th
        %tbody
          - @prevision.apartados.each do |apartado|
            %tr
              %td= apartado.rubro
              %td= number_to_currency apartado.monto_maximo
              - if @prevision == prevision_activa
                %td
                  = link_to new_gasto_path(apartado_id: apartado.id), class: 'btn btn-sm btn-success' do
                    %i.fa.fa-plus
                    Agregar gasto


.pull-right
  = link_to previsiones_path, class: 'btn btn-default' do
    %i.fa.fa-arrow-left
    Regresar
  = link_to edit_prevision_path(@prevision), class: 'btn btn-primary' do
    %i.fa.fa-edit
    Modificar