config/routes.rb
Rails.application.routes.draw do
  resources :comisiones
  resources :topes
  get 'home/index'
  get 'home/estado_cuenta', as: :estado_cuenta

  resources :gastos
  resources :socios
  resources :proveedores
  resources :depositos
  resources :apartados, only: [:show]
  resources :previsiones
  resources :rubros
  resource :prevision_activa, only: [:show, :update]
  devise_for :usuarios, skip: [:registrations]

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :no_socio and return if Socio.count == 0
    render :no_rubro and return if Rubro.count == 0
    render :no_prevision and return if Prevision.count == 0
    render :no_prevision_activa and return if Prevision.default.nil?
    render :no_deposito and return if Deposito.count == 0

    @prevision = prevision_activa
  end

  def estado_cuenta
    @mas_iva = params[:mas_iva]
    @estado_cuenta = EstadoCuenta.build(prevision: prevision,
                                        rango_fechas: rango_fechas,
                                        mas_iva: params[:mas_iva])
    respond_to do |format|
      format.html
      format.xls { send_data(xls_file, filename: 'estado_cuenta.xls') }
    end
  end

private

  def xls_file
    @estado_cuenta.to_xls
  end

  def prevision
    @prevision ||= Prevision.
      includes(gastos: [:socio, apartado: :rubro]).
      de_periodo(prevision_activa.periodo)
  end

  def rango_fechas
    @rango_fechas ||= RangoFechasEstadoCuenta.new(params[:mes], year)
  end

  def year
    prevision_activa.periodo
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def mostrar_montos(monto:, monto_limite:, ocultar_limite: false)
    riesgo_montos = RiesgoMontos.build monto: monto, monto_limite: monto_limite
    if ocultar_limite
      mostrar_monto(riesgo_montos)
    else
      mostrar_monto(riesgo_montos) + mostrar_monto_limite(riesgo_montos)
    end
  end

  def mostrar_monto(riesgo_montos)
    content_tag :span, class: "riesgo-#{riesgo_montos.riesgo}" do
      number_to_currency(riesgo_montos.monto)
    end
  end

  def mostrar_monto_limite(riesgo_montos)
    " / " + number_to_currency(riesgo_montos.monto_limite)
  end
end

app/views/home/_depositos.html.haml
%h3 Depósitos

%table.table
  %thead
    %tr
      %th Fecha
      %th Previsión
      %th Monto

  %tbody
    - @prevision.depositos.each do |deposito|
      %tr
        %td= deposito.fecha
        %td= deposito.prevision
        %td= number_to_currency deposito.monto
  %tfoot
    %th
    %th
    %th= number_to_currency @prevision.monto_depositado

app/views/home/_estado_cuenta.html.haml
%h2 Estado de cuenta

%hr/

%table.table
  %thead
    %tr
      %th Fecha
      %th Descripción
      %th Método de pago
      %th Cargo
      %th Abono

  %tbody
    - @movimientos.each do |movimiento|
      %tr
        %td= movimiento.fecha
        %td= movimiento.descripcion
        %td= movimiento.metodo
        %td= number_to_currency movimiento.cargo
        %td= number_to_currency movimiento.abono

app/views/home/_gastos.html.haml
%h3 Gastos

%table.table
  %thead
    %tr
      %th Fecha
      %th Socio
      %th Apartado
      %th Monto

  %tbody
    - Gasto.para_listado.each do |gasto|
      %tr
        %td= gasto.fecha
        %td= gasto.socio
        %td= gasto.apartado
        %td= number_to_currency gasto.monto
  %tfoot
    %th
    %th
    %th
    %th= number_to_currency Gasto.sum(:monto)

app/views/home/_no_resource.html.haml
#home
  .no-data
    %h1.text-center.text-error= message

    .text-center
      .control-group
        = link_to new_resource_path, class: 'btn btn-lg btn-primary' do
          %i.fa.fa-plus
          = button_label

app/views/home/estado_cuenta.html.haml
.col-md-12
  %h2 Estado de cuenta

.row.mb-3
  .col-md-8
    = form_tag estado_cuenta_path, method: :get, class: "form-inline" do
      = label_tag :mes, "Mes", class: "sr-only mr-2"
      = text_field_tag :mes, params[:mes], placeholder: "Selecciona el mes", class: "mr-2 form-control"
      %label.form-check-label.mr-2
        = check_box_tag :mas_iva, true, @mas_iva, class: "form-check-input"
        Incluir IVA
      = submit_tag "Filtrar", class: "btn btn-primary mr-2"
      = link_to "Cancelar", estado_cuenta_path, class: "btn btn-danger"

  .col-md-4
    %label Saldo inicial
    = number_to_currency @estado_cuenta.saldo_inicial
    %label Saldo final
    = number_to_currency @estado_cuenta.saldo_final
%hr/

%table#estado_cuenta.table.table-striped.table-hover
  %thead
    %tr
      %th Fecha
      %th Descripción
      %th Método de pago
      %th Cargo
      %th Abono

  %tbody
    - @estado_cuenta.movimientos.each do |movimiento|
      %tr
        %td= movimiento.fecha
        %td= movimiento.descripcion
        %td= movimiento.metodo
        %td= number_to_currency movimiento.cargo
        %td= number_to_currency movimiento.abono
  %tfoot
    %tr
      %td Total
      %td
      %td
      %td= number_to_currency @estado_cuenta.total_cargos
      %td= number_to_currency @estado_cuenta.total_abonos

= link_to estado_cuenta_path({ format: :xls }.merge(params.permit(:mas_iva, :mes).to_h)), class: 'btn btn-lg btn-primary' do
  %i.fa.fa-file-excel-o
  Descargar xls

app/views/home/index.html.haml
.float-right
  = link_to estado_cuenta_path, class: 'btn btn-lg btn-primary' do
    %i.fa.fa-table
    Ver Estado de Cuenta

%h1
  %i.fa.fa-heartbeat
  &nbsp;
  Panel de control
%hr

.row
  .col-md-6
    .card.mb-3
      .card-header
        Montos generales
      %ol.list-group.list-group-flush
        %li.list-group-item.justify-content-between
          = link_to "Total", @prevision
          .float-right= number_to_currency @prevision.monto
        %li.list-group-item.justify-content-between
          = link_to "Depositado", depositos_path
          .float-right= number_to_currency @prevision.monto_depositado
        %li.list-group-item.justify-content-between
          = link_to "Gastado", gastos_path
          .float-right= mostrar_montos monto: @prevision.monto_gastado, monto_limite: @prevision.monto, ocultar_limite: true
        %li.list-group-item.justify-content-between
          = link_to "Reservado", gastos_path
          .float-right= mostrar_montos monto: @prevision.monto_reservado, monto_limite: @prevision.monto, ocultar_limite: true
        %li.list-group-item.justify-content-between
          = link_to "Gastado + reservado", gastos_path
          .float-right= mostrar_montos monto: @prevision.monto_gastado_o_reservado, monto_limite: @prevision.monto, ocultar_limite: true
    .card
      .card-header
        Montos por socio
      %ol.list-group.list-group-flush
        - @prevision.socios.includes(:tope).each do |socio|
          %li.list-group-item.justify-content-between
            = link_to socio, socio
            .float-right= mostrar_montos(monto: socio.monto_gastado_o_reservado(prevision: @prevision), monto_limite: socio.monto_tope(prevision: @prevision))
  .col-md-6
    .card
      .card-header
        Montos por apartado
      %ol.list-group.list-group-flush
        - @prevision.apartados.includes(:gastos, :rubro).each do |apartado|
          %li.list-group-item.justify-content-between
            = link_to apartado, apartado
            .float-right= number_to_currency apartado.suma_monto_gastado

app/views/home/no_deposito.html.haml
= render 'no_resource', message: "Aún no has registrado depósitos en el sistema", new_resource_path: new_deposito_path, button_label: "Nuevo depósito"

app/views/home/no_prevision.html.haml
= render 'no_resource', message: "Aún no has ingresado una previsión al sistema", new_resource_path: new_prevision_path, button_label: "Nueva previsión"

app/views/home/no_prevision_activa.html.haml
#home
  .no-data
    %h1.text-center.text-error Aún no existe una previsión activa

    .text-center
      .control-group
        = link_to prevision_activa_path(id: Prevision.recent.first), method: :put, class: 'btn btn-lg btn-primary' do
          %i.fa.fa-check-circle
          Activar Prevision
          = Prevision.recent.first
        \
        = link_to previsiones_path, class: 'btn btn-lg btn-default' do
          %i.fa.fa-bank
          Activar otra previsión

app/views/home/no_rubro.html.haml
= render 'no_resource', message: "Aún no has ingresado rubros al sistema", new_resource_path: new_rubro_path, button_label: "Nuevo rubro"

app/views/home/no_socio.html.haml
= render 'no_resource', message: "Aún no has ingrersado un socio al sistema", new_resource_path: new_socio_path, button_label: "Nuevo socio"