config/routes.rb
Rails.application.routes.draw do
  resources :comisiones
  resources :topes
  get 'home/index'
  get 'home/estado_cuenta', as: :estado_cuenta

  resources :gastos
  resources :socios
  resources :proveedores
  resources :depositos
  resources :apartados, only: [:show]
  resources :previsiones
  resources :rubros
  resource :prevision_activa, only: [:show, :update]
  devise_for :usuarios, skip: [:registrations]

  root 'home#index'

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "es"}
  %head
    %meta{ charset: "utf-8" }/
    %meta{ content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport" }/
    %title Prev
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
      %button.navbar-toggler{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarsExampleDefault.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li{ class: controller_name == 'home' ? 'active' : '' }
            = link_to root_path, class: 'navbar-brand' do
              %i.fa.fa-heartbeat
              &nbsp;
              Prev
              = prevision_activa
        - if usuario_actual
          %ul.navbar-nav.mr-auto
            %li.nav-item{ class: controller_name == 'socios' ? 'active' : '' }
              = link_to socios_path, class: "nav-link" do
                %i.fa.fa-users
                &nbsp;
                Socios
            %li.nav-item{ class: controller_name == 'rubros' ? 'active' : '' }
              = link_to rubros_path, class: "nav-link" do
                %i.fa.fa-archive
                &nbsp;
                Rubros
            %li.nav-item{ class: controller_name == 'previsiones' ? 'active' : '' }
              = link_to previsiones_path, class: "nav-link" do
                %i.fa.fa-bank
                &nbsp;
                Previsiones
            %li.nav-item{ class: controller_name == 'depositos' ? 'active' : '' }
              = link_to depositos_path, class: "nav-link" do
                %i.fa.fa-check-square-o
                &nbsp;
                Depositos
            %li.nav-item{ class: controller_name == 'gastos' ? 'active' : '' }
              = link_to gastos_path, class: "nav-link" do
                %i.fa.fa-dollar
                &nbsp;
                Gastos
            %li.nav-item{ class: controller_name == 'comisiones' ? 'active' : '' }
              = link_to comisiones_path, class: "nav-link" do
                %i.fa.fa-credit-card
                &nbsp;
                Comisiones
            %li.nav-item{ class: controller_name == 'proveedores' ? 'active' : '' }
              = link_to proveedores_path, class: "nav-link" do
                %i.fa.fa-amazon
                &nbsp;
                Proveedores
            %li.nav-item
              = link_to destroy_usuario_session_path, class: "nav-link", method: :delete, data: { confirm: "¿Desea cerrar su sesión?" } do
                %i.fa.fa-sign-out
                Cerrar sesión

    - if usuario_actual && prevision_activa && Prevision.count > 1
      %section#banner-prevision
        .clearfix
          .container
            = link_to "Cambiar de previsión", prevision_activa_path, class: "btn btn-secondary pull-right"
            %span{ style: "vertical-align: sub" }
              La prevision activa es del
              %b
                = l prevision_activa.fecha_inicial, format: :long
                al
                = l prevision_activa.fecha_final, format: :long

    .container
      .row
        .col-sm-12.mx-auto
          = yield

    %footer.footer
      .container
        %p.text-muted
          &copy; LogicalBricks
          = Date.current.year